# ===========================================
# Site Settings
# ===========================================
# Header
site_title: 
site_description: 愿景, 不忘初心
# ---Optional ---
site_avatar: /images/TripleCrown-logo.jpg
artical_license_statement: 
# ---End Optional ---
menu:
  Home: /
  Archives: /archives
  AboutMe: /about

# display widgets
widgets:
- search
- archives
- recent_posts
- tagcloud
- social_links

# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon:

# ===========================================
# Miscellaneous Settings
# ===========================================
# 搜索引擎统计，取消
# Baidu Analytics
# baidu_analytics: 542b4962c3c4035fce9071b7c665f0d2
# Google Analytics
# google_analytics: UA-97838175-1
# addthis_analytics: ra-5d3d630390ef40ae
# Disqus
disqus:
  enable: false
  shortname: 
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: false
  shortname: 
# Visitors
# 记录访问游客
leancloud_visitors:
  enable: false
  app_id: 
  app_key: 
  server_url: 
# 开启捐赠按钮
donation:
  enable: false
  # alipay: /images/alipay-qr.png
  # wechat: /images/wechat-qr.png

# Search 
# Note: please install hexo-generator-search plugin and config the root _config.yml (not theme's _config.yml) as below value search.json(https://www.npmjs.com/package/hexo-generator-search):
#search:
#  path: search.json
#  field: post
# 底部的条目
infinite:
  enable: false
  title1: 
  title2: 

# 自定义
# 设置菜单能够随着页面滚动而固定
scrollmenu:
  enable: true
